server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
spring:
    thymeleaf:
     cache: false
     prefix: classpath:/templates/
     suffix: .html
     encoding: UTF-8
     content-type: text/html
     mode: HTML5
    mvc:
      static-path-pattern: /** 
    resources:
      static-locations:
        - classpath:/static/
    datasource:
        name: advertisement 
        url: jdbc:mysql://127.0.0.1:3306/advertisement?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
        username: root
        password: 1019315
        #使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        tomcat:
          initial-size: 20
          max-active: 100
          max-idle: 5
          max-wait: 10000
          min-idle: 1
          test-on-borrow: true
          validation-query: SELECT 1
          
mybatis: 
  mapperLocations: classpath:com/it/advertisement/mapper/*.xml
  typeAliasesPackage: com.it.advertisement.entity